        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-white-800">Dashboard</h1>
          </div>

          <!-- Content Row -->
          <div class="row text-center">
            <div class="col-xl-12 col-lg-12">
              <div class="card shadow md=4">
                <div class="card-body">
                 <h2>SELAMAT DATANG DI PUSKESMAS CIKUNDUL</h2>
                 <h3>""</h3>
                </div>   
              </div>
            </div>
          </div>

          
        <!-- /.container-fluid -->
        </div>
      </div>
      <!-- End of Main Content -->
